# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "21"
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Checkout IMI Maven Parent
        uses: actions/checkout@v4
        with:
          repository: imi-frankfurt/maven
          ref: 37dab8a52e2c38cb5d45a1c59cacaf4070c668ba
      - name: Build IMI Maven Parent
        run: mvn install -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
      - name: Checkout IMI Spring Parent
        uses: actions/checkout@v4
        with:
          repository: imi-frankfurt/maven.spring
          ref: d716857d7e60d7e5a8fb213b93ea30c75958ad12
      - name: Build IMI Spring Parent
        run: mvn install -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
      - name: Checkout DataElementHub Parent
        uses: actions/checkout@v4
        with:
          repository: imi-frankfurt/dataelementhub.maven
          ref: 2bffcdf94cb2e210caa9ea67f84bf8b2e4e56612
      - name: Build Build DataElementHub Parent
        run: mvn install -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
      - name: Checkout DataElementHub Spring Parent
        uses: actions/checkout@v4
        with:
          repository: imi-frankfurt/dataelementhub.maven.spring
          ref: 657516f56f73d7ab07872a3bf736bf258c7e018c
      - name: Build DataElementHub Spring Parent
        run: sed -i 's/<version>12.0.0<\/version>/<version>13.0.0<\/version>/' pom.xml && mvn install -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
      - name: Checkout DataElementHub DAL
        uses: actions/checkout@v4
        with:
          repository: imi-frankfurt/dataelementhub.dal
          ref: 1f9cb07c4fed12dba3c09a846e89150c222efbf0
      - name: Build DataElementHub DAL
        run: mvn install -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
      - name: Checkout DataElementHub Model
        uses: actions/checkout@v4
        with:
          repository: imi-frankfurt/dataelementhub.model
          ref: 0ae6275653b8b997253a1e7ad04549f95367d504
      - name: Build DataElementHub Model
        run: sed -i 's/<version>11.3.0<\/version>/<version>13.0.0<\/version>/' pom.xml && sed -i 's/<version>1.18.24<\/version>/<version>1.18.30<\/version>/' pom.xml && mvn install -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
      - uses: actions/checkout@v4
      - name: Build with Maven
        run: mvn install
